SKILL_KEYWORDS = [
    "python",
    "sql",
    "machine learning",
    "deep learning",
    "data analysis",
    "data science",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "nlp",
    "computer vision",
    "generative ai",
    "genai",
    "llm",
    "langchain",
    "rag",
    "streamlit",
    "flask",
    "fastapi",
    "django",
    "api",
    "aws",
    "azure",
    "gcp",
    "google cloud",
    "docker",
    "kubernetes",
    "mlops",
    "git",
    "github",
    "linux",
    "excel",
    "power bi",
    "tableau",
    "etl",
    "data pipeline",
    "data engineering",
    "spark",
    "hadoop",
    "airflow",
    "mongodb",
    "postgresql",
    "mysql",
    "cloud",
]


FIELDS = [
        "title",
        "jobTitle",
        "positionName",
        "description",
        "descriptionText",
        "descriptionHtml",
        "skills",
        "attributes",
        "requirements",
        "job_type",
        "jobType",
        "job_level",
        "job_function",
        "company_industry",
    ]
